### ISSUE TITLE
Auto Breaker World Corruption MC-1.12.2

### ISSUE THREAD

**Issue by HexStudios** [Ellpeck/ActuallyAdditions#1044]
I was playing my survival world when I had the bright idea to automate concrete production, so I placed an auto placer to place the powder, and the auto-breaker to break the concrete, when suddenly the wold crashed and is now un-playable do to this  game breaking bug as seen below:

``[22:24:54] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:771) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=color, clazz=class net.minecraft.item.EnumDyeColor, values=[white, orange, magenta, lightBlue, yellow, lime, pink, gray, silver, cyan, purple, blue, brown, green, red, black]} as it does not exist in BlockStateContainer{block=actuallyadditions:block_breaker, properties=[facing]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201) ~[awu$a.class:?]
	at net.minecraft.block.BlockColored.func_180651_a(SourceFile:26) ~[apn.class:?]
	at net.minecraft.block.Block.getDrops(Block.java:1323) ~[aow.class:?]
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityBreaker.doWork(TileEntityBreaker.java:88) ~[TileEntityBreaker.class:?]
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityBreaker.updateEntity(TileEntityBreaker.java:64) ~[TileEntityBreaker.class:?]
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityBase.func_73660_a(TileEntityBase.java:228) ~[TileEntityBase.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1832) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) ~[MinecraftServer.class:?]
	... 4 more
[22:24:54] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Chris\AppData\Roaming\.minecraft\crash-reports\crash-2018-03-09_22.24.54-server.txt
[22:24:54] [Server thread/INFO]: Stopping server``

Info: I am currently running Minecraft 1.12.2, Forge 1.12.2-14.23.1.2600, and the latest version of Actually Additions. Any help would be appreciated as I am now locked out of my world that I progressed so much on!

**Comment by canitzp** [comment]
We can never be sure what your "latest" version is. It would be the best if you can send us the crash report file, it contains valuable information bout your mc setup. So far this bug is a bit strange, but I have no clue how the code is structured

**Comment by Shadows-of-Fire** [comment]
Either a blockpos or a blockstate that's incorrect is being passed to some method, bleh.
For now, enable remove erroring tile entities in forge.cfg so your world works.
