### ISSUE TITLE
[1.9.4] Server crash on startup

### ISSUE THREAD

**Issue by kwpugh** [Ellpeck/ActuallyAdditions#109]
Forge: 1954
Mod: ActuallyAdditions-1.9.4-r40.jar

crash report: http://pastebin.com/raw/rka4HfWE

**Comment by Ellpeck** [comment]
Update Forge.

**Comment by kwpugh** [comment]
Updated to latest forge.

Got these messages for each DIM on the server:

[11:22:19] [Server thread/ERROR] [Actually Additions]: Something went wrong trying to save WorldData for world 2!
java.io.FileNotFoundException: ./world/DIM2/data/actuallyadditionsdata2.dat (Is a directory)
        at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_91]
        at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[?:1.8.0_91]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[?:1.8.0_91]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[?:1.8.0_91]
        at de.ellpeck.actuallyadditions.mod.data.WorldData.save(WorldData.java:103) [WorldData.class:?]
        at de.ellpeck.actuallyadditions.mod.event.WorldLoadingEvents.onSave(WorldLoadingEvents.java:33) [WorldLoadingEvents.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_346_WorldLoadingEvents_onSave_Save.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1012) [lq.class:?]
        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:354) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:634) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

Anything to worry about?

**Comment by Ellpeck** [comment]
No, should be fine.

**Comment by kwpugh** [comment]
The messages keep repeating on the server console, FYI.

**Comment by Ellpeck** [comment]
Yes, I noticed this, sorry.
There will be an updated version of r40 on curse in a couple of minutes. Please download that and put it onto the server, and then go to the "data"-folder of the world and every DIM-X folder and delete the actuallyadditions things. Sorry for that :(
