### ISSUE TITLE
[Crash] [1.12.2] Startup Crash in AA r136 in Foolcraft 3

### ISSUE THREAD

**Issue by WonderDog** [Ellpeck/ActuallyAdditions#1121]
Version _ActuallyAdditions-1.12.2-r136.jar_ has an exception in Foolcraft 3 loading Minecraft 1.12.2.

Rollback to r135 and game starts.

Error snip:
 `net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Actually Additions (actuallyadditions)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at de.ellpeck.actuallyadditions.mod.recipe.CrusherRecipeRegistry.removeDuplicateRecipes(CrusherRecipeRegistry.java:71)
	at de.ellpeck.actuallyadditions.mod.recipe.CrusherRecipeRegistry.registerFinally(CrusherRecipeRegistry.java:62)
	at de.ellpeck.actuallyadditions.mod.crafting.CrusherCrafting.init(CrusherCrafting.java:119)
	at de.ellpeck.actuallyadditions.mod.ActuallyAdditions.postInit(ActuallyAdditions.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`

Full crash log at [Minecraft Crash Report - AA r136](https://pastebin.com/VnLTKwGj)

**Comment by Shadows-of-Fire** [comment]
Does [this build](https://1drv.ms/u/s!AoXVxSo6VrNfgZYxW4ePs80_bpLGew) resolve the issue?

**Comment by Centros** [comment]
Just got the same error on ActuallyAdditions-1.12.2-r136 
[crash-2018-06-22_22.08.42-client.txt](https://github.com/Ellpeck/ActuallyAdditions/files/2129559/crash-2018-06-22_22.08.42-client.txt)
