### ISSUE TITLE
Game crash with modtweaker

### ISSUE THREAD

**Issue by red360** [Ellpeck/ActuallyAdditions#1131]
Versions ActuallyAdditions-1.12.2-r136-hotfix3 and hotfix4 causes game crash with modtweaker.
ActuallyAdditions-1.12.2-r136-hotfix2 no crash.

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.7.4.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.31.jar)
  CTMCorePlugin (CTM-MC1.12-0.3.0.15.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  FMLPlugin (elulib-0.1.12.jar)
  LoadingPlugin (Quark-r1.4-125.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b155.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.8.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 6/24/18 10:48 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mod Tweaker (modtweaker)
Caused by: java.lang.IllegalAccessError: tried to access field de.ellpeck.actuallyadditions.api.recipe.EmpowererRecipe.output from class com.blamejared.compat.actuallyaddition.Empowerer$Add
	at com.blamejared.compat.actuallyaddition.Empowerer$Add.getRecipeInfo(Empowerer.java:46)
	at com.blamejared.compat.actuallyaddition.Empowerer$Add.getRecipeInfo(Empowerer.java:38)
	at com.blamejared.mtlib.utils.BaseListModification.getRecipeInfo(BaseListModification.java:24)
	at com.blamejared.mtlib.utils.BaseListAddition.describe(BaseListAddition.java:42)
	at crafttweaker.runtime.CrTTweaker.apply(CrTTweaker.java:49)
	at crafttweaker.CraftTweakerAPI.apply(CraftTweakerAPI.java:135)
	at java.lang.Iterable.forEach(Unknown Source)
	at com.blamejared.ModTweaker.loadComplete(ModTweaker.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 810664504 bytes (773 MB) / 4817326080 bytes (4594 MB) up to 8375238656 bytes (7987 MB)
	JVM Flags: 22 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m -Xmn2048m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseNUMA -XX:+CMSIncrementalPacing -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=20000 -XX:ParallelGCThreads=4
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 197 mods loaded, 197 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

**Comment by Shadows-of-Fire** [comment]
Modtweaker currently does not support r136.
