### ISSUE TITLE
Auto-Placer NPE error spam

### ISSUE THREAD

**Issue by Sir-Will** [Ellpeck/ActuallyAdditions#1237]
Getting this error spam:

ActuallyAdditions-1.12.2-r146
```
[14:56:42] [Server thread/ERROR]: [Actually Additions]: Something that places Blocks at -2675, 69, 3053 in World 0 threw an Exception! Don't let that happen again!
java.lang.NullPointerException: null
	at net.minecraft.entity.player.EntityPlayerMP.func_71110_a(EntityPlayerMP.java:989) ~[oq.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71120_a(EntityPlayerMP.java:984) ~[oq.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1293) ~[or.class:?]
	at de.ellpeck.actuallyadditions.mod.util.WorldUtil.useItemAtSide(WorldUtil.java:193) [WorldUtil.class:?]
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityBreaker.doWork(TileEntityBreaker.java:100) [TileEntityBreaker.class:?]
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityBreaker.updateEntity(TileEntityBreaker.java:65) [TileEntityBreaker.class:?]
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityBase.func_73660_a(TileEntityBase.java:223) [TileEntityBase.class:?]
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:229) [TrackingUtil.class:1.12.2-2768-7.1.6-RC3616]
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2985) [oo.class:?]
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zmd000(WorldServer.java:2972) [oo.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:6740) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2291) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[14:56:43] [Server thread/ERROR]: [Actually Additions]: Something that places Blocks at -2701, 69, 3028 in World 0 threw an Exception! Don't let that happen again!
java.lang.NullPointerException: null
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1341) ~[or.class:?]
	at de.ellpeck.actuallyadditions.mod.util.WorldUtil.useItemAtSide(WorldUtil.java:193) [WorldUtil.class:?]
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityBreaker.doWork(TileEntityBreaker.java:100) [TileEntityBreaker.class:?]
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityBreaker.updateEntity(TileEntityBreaker.java:65) [TileEntityBreaker.class:?]
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityBase.func_73660_a(TileEntityBase.java:223) [TileEntityBase.class:?]
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:229) [TrackingUtil.class:1.12.2-2768-7.1.6-RC3616]
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2985) [oo.class:?]
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zmd000(WorldServer.java:2972) [oo.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:6740) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2291) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

![](https://i.imgur.com/eYIjAbQ.jpg)
![](https://i.imgur.com/hnkpbbp.jpg)

**Comment by runescapejon** [comment]
I am having the same issue https://pastebin.com/raw/6mXXqvt4

**Comment by Sir-Will** [comment]
This change would probably help with it: https://github.com/Ellpeck/ActuallyAdditions/issues/1020
