### ISSUE TITLE
Client crashed when trying to load the mod

### ISSUE THREAD

**Issue by SkilledTheGamer** [Ellpeck/ActuallyAdditions#1256]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2019-05-10 18:18:29 ICT
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Actually Additions (actuallyadditions)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/common/IRarity
    at de.ellpeck.actuallyadditions.mod.fluids.InitFluids.registerFluidBlock(InitFluids.java:55)
    at de.ellpeck.actuallyadditions.mod.fluids.InitFluids.init(InitFluids.java:40)
    at de.ellpeck.actuallyadditions.mod.ActuallyAdditions.preInit(ActuallyAdditions.java:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.common.IRarity
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 43 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (x86) version 6.1
  Java Version: 1.8.0_211, Oracle Corporation
  Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
  Memory: 141002384 bytes (134 MB) / 348557312 bytes (332 MB) up to 1144258560 bytes (1091 MB)
  JVM Flags: 3 total; -Xmn128M -Xmx1103M -XX:+UseConcMarkSweepGC
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2811 24 mods loaded, 24 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                  | Version           | Source                                              | Signature                                |
       |:----- |:------------------- |:----------------- |:--------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft           | 1.12.2            | minecraft.jar                                       | None                                     |
       | LCH   | mcp                 | 9.42              | minecraft.jar                                       | None                                     |
       | LCH   | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2811.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge               | 14.23.5.2811      | forge-1.12.2-14.23.5.2811.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCE   | actuallyadditions   | 1.12.2-r147       | ActuallyAdditions-1.12.2-r147.jar                   | None                                     |
       | LC    | aroma1997core       | 2.0.0.2           | Aroma1997Core-1.12.2-2.0.0.2.jar                    | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LC    | aroma1997sdimension | 2.0.0.2.b92       | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b92.jar | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LC    | baubles             | 1.5.2             | Baubles-1.12-1.5.2.jar                              | None                                     |
       | LC    | bettermagnets       | 0.1               | bettermagnets-mc1.12.x-v1.11.jar                    | None                                     |
       | LC    | chesttransporter    | 2.8.8             | ChestTransporter-1.12.2-2.8.8.jar                   | None                                     |
       | LC    | jei                 | 4.15.0.275        | jei_1.12.2-4.15.0.275.jar                           | None                                     |
       | LC    | cyclicmagic         | 1.18.6            | Cyclic-1.12.2-1.18.6.jar                            | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
       | LC    | forgelin            | 1.8.2             | Forgelin-1.8.2.jar                                  | None                                     |
       | LC    | mantle              | 1.12-1.3.3.49     | Mantle-1.12-1.3.3.49.jar                            | None                                     |
       | LC    | tconstruct          | 1.12.2-2.12.0.135 | TConstruct-1.12.2-2.12.0.135.jar                    | None                                     |
       | LC    | exnihilocreatio     | 1.12.2-0.4.2      | exnihilocreatio-1.12.2-0.4.2.jar                    | None                                     |
       | LC    | gwgmcgenmod         | 1.4               | gmcgenmod-mc1.12-v1.4.jar                           | None                                     |
       | LC    | gravestone          | 1.10.2            | gravestone-1.10.2.jar                               | None                                     |
       | LC    | ironchest           | 1.12.2-7.0.59.842 | ironchest-1.12.2-7.0.59.842.jar                     | None                                     |
       | LC    | ironfurnaces        | 1.3.3             | ironfurnaces-1.3.3.jar                              | None                                     |
       | LC    | lootbags            | 2.5.8.5           | LootBags-1.12.2-2.5.8.5.jar                         | None                                     |
       | LC    | storagenetwork      | 1.6.6             | SimpleStorageNetwork-1.12.2-1.6.6.jar               | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
       | LC    | tp                  | 3.2.32            | tinyprogressions-1.12.2-3.3.32-Release.jar          | None                                     |
       | LC    | vanillafix          | 1.0.10-SNAPSHOT   | VanillaFix-1.0.10-99.jar                            | None                                     |
  Loaded coremods (and transformers): VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
                                        
                                      ForgelinPlugin (Forgelin-1.8.2.jar)
  GL info: ' Vendor: 'VMware, Inc.' Version: '2.1 Mesa 10.0.2 (git-675cd84)' Renderer: 'Gallium 0.4 on llvmpipe (LLVM 3.4, 128 bits)'
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
  Suspected Mods: Actually Additions (actuallyadditions)
  Launched Version: Forge 1.12.2
  LWJGL: 2.9.4
  OpenGL: Gallium 0.4 on llvmpipe (LLVM 3.4, 128 bits) GL version 2.1 Mesa 10.0.2 (git-675cd84), VMware, Inc.
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 2x Intel(R) Core(TM)2 Duo CPU E4600 @ 2.40GHz

**Comment by Shadows-of-Fire** [comment]
update forge

**Comment by flibberdee** [comment]
@Shadows-of-Fire ROFL. I had the same error. I feel like such a putz. Thanks!
