### ISSUE TITLE
error with c2me

### ISSUE THREAD

**Issue by coco875** [Ellpeck/ActuallyAdditions#1415]
c2me report a error with actually additions

```
[18oct.2024 21:28:40.329] [Worker-Main-9/ERROR] [CheckedThreadLocalRandom/]: ThreadLocalRandom accessed from a different thread (owner: Render thread, current: Worker-Main-9)
This is usually NOT a bug in C2ME, but a bug in another mod or in vanilla code. 
Possible solutions: 
  - Find possible causes in the stack trace below and 
    - if caused by another mod, report this to the corresponding mod authors 
    - if no other mods are involved, report this to C2ME 

java.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Render thread, current: Worker-Main-9)
	at TRANSFORMER/c2me_fixes_worldgen_threading_issues@0.3.0alpha.0.2901.21.1/com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.handleNotOwner(CheckedThreadLocalRandom.java:55) ~[c2me-fabric-mc1.21.1-0.3.0+alpha.0.290$c2me-fixes-worldgen-threading-issues-mc1.21.1-0.3.0+alpha.0.290_mapped_moj_1.21.1.jar%231248!/:?]
	at TRANSFORMER/c2me_fixes_worldgen_threading_issues@0.3.0alpha.0.2901.21.1/com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.isSafe(CheckedThreadLocalRandom.java:38) ~[c2me-fabric-mc1.21.1-0.3.0+alpha.0.290$c2me-fixes-worldgen-threading-issues-mc1.21.1-0.3.0+alpha.0.290_mapped_moj_1.21.1.jar%231248!/:?]
	at TRANSFORMER/c2me_fixes_worldgen_threading_issues@0.3.0alpha.0.2901.21.1/com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.next(CheckedThreadLocalRandom.java:86) ~[c2me-fabric-mc1.21.1-0.3.0+alpha.0.290$c2me-fixes-worldgen-threading-issues-mc1.21.1-0.3.0+alpha.0.290_mapped_moj_1.21.1.jar%231248!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.BitRandomSource.nextInt(BitRandomSource.java:33) ~[client-1.21.1-20240808.144430-srg.jar%23342!/:?]
	at TRANSFORMER/actuallyadditions@1.3.3+mc1.21.1/de.ellpeck.actuallyadditions.mod.blocks.BlockAtomicReconstructor$TheItemBlock.appendHoverText(BlockAtomicReconstructor.java:168) ~[ActuallyAdditions-1.3.3+mc1.21.1.jar%23345!/:1.3.3+mc1.21.1]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.ItemStack.getTooltipLines(net/minecraft/world/item/ItemStack.java:770) ~[client-1.21.1-20240808.144430-srg.jar%23342!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.multiplayer.SessionSearchTrees.lambda$getTooltipLines$0(net/minecraft/client/multiplayer/SessionSearchTrees.java:51) ~[client-1.21.1-20240808.144430-srg.jar%23342!/:?]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?]
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.searchtree.SearchTree.plainText(SearchTree.java:21) ~[client-1.21.1-20240808.144430-srg.jar%23342!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.searchtree.FullTextSearchTree.<init>(FullTextSearchTree.java:16) ~[client-1.21.1-20240808.144430-srg.jar%23342!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.multiplayer.SessionSearchTrees.lambda$updateCreativeTooltips$14(net/minecraft/client/multiplayer/SessionSearchTrees.java:125) ~[client-1.21.1-20240808.144430-srg.jar%23342!/:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
```

**Comment by Shadows-of-Fire** [comment]
This method needs to be updated to use the tooltip context
https://github.com/Ellpeck/ActuallyAdditions/blob/0ac1e81d0e335c2f19978cdf0b3b16e3a25ed9a4/src/main/java/de/ellpeck/actuallyadditions/mod/blocks/BlockAtomicReconstructor.java#L166

**Comment by coco875** [comment]
just saw the commit now

**Comment by Mrbysco** [comment]
A new jar has been uploaded and will be available shortly

**Comment by coco875** [comment]
test and it work
