### ISSUE TITLE
last Version (R8) crash when you try to look at a recipe in NEI

### ISSUE THREAD

**Issue by bloodyraoul** [Ellpeck/ActuallyAdditions#23]
java.lang.ExceptionInInitializerError
at ellpeck.actuallyadditions.nei.BookletInfoRecipeHandler.loadCraftingRecipes(BookletInfoRecipeHandler.java:69)
at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:331)
at ellpeck.actuallyadditions.nei.BookletInfoRecipeHandler.loadCraftingRecipes(BookletInfoRecipeHandler.java:62)
at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:466)
at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:23)
at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307)
at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java)
at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475)
at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465)
at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException

**Comment by Ellpeck** [comment]
Just any recipe at any point? O.o
