### ISSUE TITLE
Server crash maybe caused by Actually Additions?

### ISSUE THREAD

**Issue by phit** [Ellpeck/ActuallyAdditions#247]
Crashlog & End of server log file https://gist.github.com/phit/91f1505b8de42c1cf1701b69edab2473
I've been trying to hunt down this crash for a while, today I noticed [this line](https://gist.github.com/phit/91f1505b8de42c1cf1701b69edab2473#file-end-of-server-logfile-L21) right before the crash, so I figured maybe its AA.
Thanks in advance if you take the time to look into it!

edit: the dimension in question is added by [Simple Dimensions](https://minecraft.curseforge.com/projects/simple-dimensions)

**Comment by phit** [comment]
just happened again, crashlog is pretty much the same
this time the server log looks different though, relevant part:
```
[16:05:48] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save world
[16:05:49] [Server thread/INFO] [Actually Additions/]: Unloading WorldData for world 0!
[16:05:49] [Server thread/INFO] [Actually Additions/]: Unloading WorldData for world -1!
[16:05:49] [Server thread/INFO] [Actually Additions/]: Unloading WorldData for world 1!
[16:05:49] [Server thread/INFO] [Actually Additions/]: Unloading WorldData for world 30000!
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: java.io.IOException: Stream Closed
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at java.io.RandomAccessFile.seek0(Native Method)
[16:05:49] [Server thread/INFO] [FML/]: Unloading dimension 0
[16:05:49] [Server thread/INFO] [FML/]: Unloading dimension -1
[16:05:49] [Server thread/INFO] [FML/]: Unloading dimension 1
[16:05:49] [Server thread/INFO] [FML/]: Unloading dimension 30000
[16:05:49] [Server thread/DEBUG] [FML/]: Reverting to frozen data state.
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at java.io.RandomAccessFile.seek(RandomAccessFile.java:557)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at net.minecraft.world.chunk.storage.RegionFile.func_76712_a(RegionFile.java:299)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at net.minecraft.world.chunk.storage.RegionFile.func_76706_a(RegionFile.java:220)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at net.minecraft.world.chunk.storage.RegionFile$ChunkBuffer.close(RegionFile.java:356)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:241)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_183013_b(AnvilChunkLoader.java:243)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75814_c(AnvilChunkLoader.java:220)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75818_b(AnvilChunkLoader.java:260)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at net.minecraft.world.gen.ChunkProviderServer.func_104112_b(ChunkProviderServer.java:243)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at net.minecraft.world.WorldServer.func_104140_m(WorldServer.java:1031)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at btfubackup.WorldSavingControl$$anonfun$saveOffAndFlush$1.apply(WorldSavingControl.scala:13)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at btfubackup.WorldSavingControl$$anonfun$saveOffAndFlush$1.apply(WorldSavingControl.scala:8)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at btfubackup.WorldSavingControl$.saveOffAndFlush(WorldSavingControl.scala:8)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at btfubackup.BackupProcess.btfubackup$BackupProcess$$task(BTFUPerformer.scala:84)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at btfubackup.BackupProcess$$anonfun$1.apply$mcV$sp(BTFUPerformer.scala:60)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at btfubackup.BackupProcess$$anonfun$1.apply(BTFUPerformer.scala:60)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at btfubackup.BackupProcess$$anonfun$1.apply(BTFUPerformer.scala:60)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[16:05:49] [ForkJoinPool-1-worker-13/INFO] [STDERR/]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:293]: 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[16:05:49] [ForkJoinPool-1-worker-13/ERROR] [Actually Additions/]: Tried to save WorldData for -1 without any data handler being present!?
[16:05:49] [ForkJoinPool-1-worker-13/ERROR] [Actually Additions/]: Tried to save WorldData for 1 without any data handler being present!?
[16:05:49] [ForkJoinPool-1-worker-13/ERROR] [Actually Additions/]: Tried to save WorldData for 30000 without any data handler being present!?
[16:05:49] [Server thread/TRACE] [mcp/mcp]: Sending event FMLModIdMappingEvent to mod mcp
[16:05:49] [Server thread/TRACE] [mcp/mcp]: Sent event FMLModIdMappingEvent to mod mcp
[16:05:49] [Server thread/DEBUG] [FML/]: Bar Step: ModIdMapping - Minecraft Coder Pack took 0.001s
[16:05:49] [Server thread/TRACE] [FML/FML]: Sending event FMLModIdMappingEvent to mod FML
[16:05:49] [Server thread/TRACE] [FML/FML]: Sent event FMLModIdMappingEvent to mod FML
[16:05:49] [Server thread/DEBUG] [FML/]: Bar Step: ModIdMapping - Forge Mod Loader took 0.000s
[16:05:49] [Server thread/TRACE] [Forge/Forge]: Sending event FMLModIdMappingEvent to mod Forge
[16:05:50] [Server thread/TRACE] [Forge/Forge]: Sent event FMLModIdMappingEvent to mod Forge
[16:05:50] [Server thread/DEBUG] [FML/]: Bar Step: ModIdMapping - Minecraft Forge took 0.611s
```

I think it might not be Actually Additions after all, gonna try updating BTFU

**Comment by Ellpeck** [comment]
Yes, this is really strange.
If you're unsure, try removing mods in batches and see if it goes away :D

**Comment by Ellpeck** [comment]
I'm closing this for now as I am pretty sure this is an issue with the backup mod.
If it isn't please reopen this issue!
