### ISSUE TITLE
Laser Energy Relay causing game crash

### ISSUE THREAD

**Issue by Fryvisuals** [Ellpeck/ActuallyAdditions#445]
I recently moved my laser energy relay that was connected to my Ender IO capacitor bank and Environmental Tech tier 1 solar panel. When I went to reconnect the relays with the wrench, the game crashed and continues to crash on startup. I read through the error log and noticed this in the log:

`Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at java.util.concurrent.ConcurrentHashMap.get(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.containsKey(Unknown Source)
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityLaserRelayEnergy.transferEnergyToReceiverInNeed(TileEntityLaserRelayEnergy.java:128)
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityLaserRelayEnergy.transmitEnergy(TileEntityLaserRelayEnergy.java:66)
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityLaserRelayEnergy.receiveEnergy(TileEntityLaserRelayEnergy.java:48)
	at de.ellpeck.actuallyadditions.mod.util.compat.TileTeslaWrapper.givePower(TileTeslaWrapper.java:35)
	at crazypants.enderio.power.tesla.TeslaToForgeAdapter.receiveEnergy(TeslaToForgeAdapter.java:23)
	at crazypants.enderio.power.forge.PowerInterfaceForge.receiveEnergy(PowerInterfaceForge.java:19)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.sendPowerTo(CapBankNetwork.java:298)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.transmitEnergy(CapBankNetwork.java:273)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.doNetworkTick(CapBankNetwork.java:229)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.access$100(CapBankNetwork.java:37)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork$TickReciever.tickEnd(CapBankNetwork.java:565)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.tickEnd(ConduitNetworkTickHandler.java:64)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.onServerTick(ConduitNetworkTickHandler.java:52)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_595_ConduitNetworkTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)`

I tried to use MCEdit to delete the block but I am unsure it even works on modded blocks. I could remove the mod from my pack but I would lose some items (not many) from Actually Additions. I did update to the latest release .87. Is there another way for fixing this?

Mod pack: All The Mods
Latest version

**Comment by Fryvisuals** [comment]
Ha thanks! Didn't know a new release happened this morning. Tried many things last night to fix it
