### ISSUE TITLE
crash on game load - latest dev release on curseforge 1.8.9-r23

### ISSUE THREAD

**Issue by biouxtai** [Ellpeck/ActuallyAdditions#50]
Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue

[1/12/2016 16:01:58 PM] 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

[1/12/2016 16:01:58 PM] 	UCE 	ActuallyAdditions{1.8.9-r23} [Actually Additions] (ActuallyAdditions-1.8.9-r23-dev.jar) 

[1/12/2016 16:01:58 PM] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[1/12/2016 16:01:58 PM] [Client thread/ERROR] [FML]: Caught exception from ActuallyAdditions
[1/12/2016 16:01:58 PM] java.lang.NoSuchFieldError: rock
[1/12/2016 16:01:58 PM] 	at de.ellpeck.actuallyadditions.mod.blocks.BlockFireworkBox.<init>(BlockFireworkBox.java:29) ~[BlockFireworkBox.class:?]
[1/12/2016 16:01:58 PM] 	at de.ellpeck.actuallyadditions.mod.blocks.InitBlocks.init(InitBlocks.java:128) ~[InitBlocks.class:?]
[1/12/2016 16:01:58 PM] 	at de.ellpeck.actuallyadditions.mod.ActuallyAdditions.preInit(ActuallyAdditions.java:70) ~[ActuallyAdditions.class:?]

No such field error: rock.

Full forge console log paste.bin'd
http://pastebin.com/ExqvX7Ln

Here is the saved crashlog from forge:
http://pastebin.com/6p0ASK7Z

**Comment by canitzp** [comment]
Are using a deobfuscated version of ActuallyAdditions or are you in a Dev-Workspace?

**Comment by biouxtai** [comment]
Good catch. Looks like I had the -dev file.  Replaced with proper download and the crash is gone.

Closing the issue.
