### ISSUE TITLE
Farmer crashing server

### ISSUE THREAD

**Issue by rileedeadeye** [Ellpeck/ActuallyAdditions#521]
Initially I thought that maybe this crash occurs when attempting to open the farmer with an item in your hand, but I am uncertain since it also happens when opening the farmer with nothing in my hand. 

Upon further investigation, when i start up my server and first log in, everything is fine, and the farmer opens ok. After the farmer collects a crop though, then when I open the farmer the crash occurs.

[02:01:23] [Server thread/INFO]: Starting minecraft server version 1.11
[02:01:36] [Server thread/INFO]: Loading properties
[02:01:36] [Server thread/INFO]: Default game type: SURVIVAL
[02:01:36] [Server thread/INFO]: Generating keypair
[02:01:36] [Server thread/INFO]: Starting Minecraft server on 216.52.148.180:25565
[02:01:36] [Server thread/INFO]: Using epoll channel type
[02:01:38] [Server thread/INFO]: Preparing level "Doomcraft"
[02:01:39] [Server thread/INFO]: [STDOUT]: settings for world: {"landScheme":"vanilla","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"medium","amplitude":1.0,"generateBopOre":true,"generateBopSoils":true,"generateBopTrees":true,"generateBopGrasses":true,"generateBopFoliage":true,"generateBopFlowers":true,"generateBopPlants":true,"generateBopWaterPlants":true,"generateBopMushrooms":true,"generateRockFormations":true,"generatePoisonIvy":true,"generateFlax":true,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateNetherPlants":true,"generateEndFeatures":true}
[02:01:39] [Server thread/INFO]: [STDOUT]: Setting up landmass VANILLA
[02:01:39] [Server thread/INFO]: [STDOUT]: ChunkProviderGenerateBOP json: {"landScheme":"vanilla","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"medium","amplitude":1.0,"generateBopOre":true,"generateBopSoils":true,"generateBopTrees":true,"generateBopGrasses":true,"generateBopFoliage":true,"generateBopFlowers":true,"generateBopPlants":true,"generateBopWaterPlants":true,"generateBopMushrooms":true,"generateRockFormations":true,"generatePoisonIvy":true,"generateFlax":true,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateNetherPlants":true,"generateEndFeatures":true}
[02:01:39] [Server thread/INFO]: [STDOUT]: ChunkProviderGenerateBOP settings: {"landScheme":"vanilla","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"medium","amplitude":1.0,"generateBopOre":true,"generateBopSoils":true,"generateBopTrees":true,"generateBopGrasses":true,"generateBopFoliage":true,"generateBopFlowers":true,"generateBopPlants":true,"generateBopWaterPlants":true,"generateBopMushrooms":true,"generateRockFormations":true,"generatePoisonIvy":true,"generateFlax":true,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateNetherPlants":true,"generateEndFeatures":true}
[02:01:40] [Server thread/ERROR]: Couldn't load loot table armorplus:entities/ender_dragon_zombie from jar:file:/servers/lgmoddedmc/minecraft/mods/armorplus-1.11-9.0.0.1-alpha.jar!/assets/armorplus/loot_tables/entities/ender_dragon_zombie.json
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'armorplus:ender_dragon_scale'
	at net.minecraft.util.JsonUtils.func_188172_b(SourceFile:122) ~[ok.class:?]
	at net.minecraft.util.JsonUtils.func_188180_i(SourceFile:133) ~[ok.class:?]
	at net.minecraft.world.storage.loot.LootEntryItem.func_186367_a(LootEntryItem.java:83) ~[bcf.class:?]
	at net.minecraft.world.storage.loot.LootEntry$Serializer.deserialize(LootEntry.java:69) ~[bch$a.class:?]
	at net.minecraft.world.storage.loot.LootEntry$Serializer.deserialize(LootEntry.java:45) ~[bch$a.class:?]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[TreeTypeAdapter.class:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[TypeAdapterRuntimeTypeWrapper.class:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[ArrayTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:868) ~[Gson.class:?]
	at com.google.gson.Gson$1.deserialize(Gson.java:126) ~[Gson$1.class:?]
	at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:437) ~[ok.class:?]
	at net.minecraft.util.JsonUtils.func_188174_a(SourceFile:445) ~[ok.class:?]
	at net.minecraft.world.storage.loot.LootPool$Serializer.deserialize(LootPool.java:144) ~[bcg$a.class:?]
	at net.minecraft.world.storage.loot.LootPool$Serializer.deserialize(LootPool.java:138) ~[bcg$a.class:?]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[TreeTypeAdapter.class:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[TypeAdapterRuntimeTypeWrapper.class:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[ArrayTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:868) ~[Gson.class:?]
	at com.google.gson.Gson$1.deserialize(Gson.java:126) ~[Gson$1.class:?]
	at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:437) ~[ok.class:?]
	at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:453) ~[ok.class:?]
	at net.minecraft.world.storage.loot.LootTable$Serializer.deserialize(LootTable.java:204) ~[bci$a.class:?]
	at net.minecraft.world.storage.loot.LootTable$Serializer.deserialize(LootTable.java:199) ~[bci$a.class:?]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:768) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:717) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:689) ~[Gson.class:?]
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:1093) ~[ForgeHooks.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.func_186518_c(LootTableManager.java:148) [bcl$a.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:71) [bcl$a.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:52) [bcl$a.class:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) [minecraft_server.1.11.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) [minecraft_server.1.11.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) [minecraft_server.1.11.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) [minecraft_server.1.11.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934) [minecraft_server.1.11.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) [minecraft_server.1.11.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) [minecraft_server.1.11.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) [minecraft_server.1.11.jar:?]
	at net.minecraft.world.storage.loot.LootTableManager.func_186521_a(LootTableManager.java:39) [bcl.class:?]
	at net.minecraft.world.storage.loot.LootTableManager.func_186522_a(LootTableManager.java:48) [bcl.class:?]
	at net.minecraft.world.storage.loot.LootTableManager.<init>(LootTableManager.java:34) [bcl.class:?]
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:151) [lw.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:256) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:267) [lh.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
[02:01:40] [Server thread/INFO]: [STDOUT]: settings for world: 
[02:01:40] [Server thread/INFO]: [STDOUT]: Setting up landmass VANILLA
[02:01:40] [Server thread/INFO]: [STDOUT]: settings for world: 
[02:01:40] [Server thread/INFO]: [STDOUT]: Setting up landmass VANILLA
[02:01:40] [Server thread/INFO]: [STDOUT]: settings for world: 
[02:01:40] [Server thread/INFO]: [STDOUT]: Setting up landmass VANILLA
[02:01:40] [Server thread/INFO]: [STDOUT]: settings for world: 
[02:01:40] [Server thread/INFO]: [STDOUT]: Setting up landmass VANILLA
[02:01:40] [Server thread/INFO]: [STDOUT]: settings for world: 
[02:01:40] [Server thread/INFO]: [STDOUT]: Setting up landmass VANILLA
[02:01:40] [Server thread/INFO]: Preparing start region for level 0
[02:01:41] [Server thread/INFO]: Preparing spawn area: 0%
[02:01:42] [Server thread/INFO]: Preparing spawn area: 36%
[02:01:43] [Server thread/INFO]: Done (5.827s)! For help, type "help" or "?"
[02:01:43] [Server thread/INFO]: Starting GS4 status listener
[02:01:43] [Query Listener #1/INFO]: Query running on 216.52.148.180:25565
[02:01:44] [Server thread/INFO]: There are 0/30 players online:
[02:01:44] [Server thread/INFO]: 
[02:01:49] [Server thread/INFO]: com.mojang.authlib.GameProfile@19ca9570[id=<null>,name=Rileedeadeye,properties={},legacy=false] (/97.84.140.124:49780) lost connection: Disconnected
[02:01:55] [Server thread/INFO]: com.mojang.authlib.GameProfile@70cdd5d4[id=<null>,name=Rileedeadeye,properties={},legacy=false] (/97.84.140.124:49786) lost connection: Disconnected
[02:02:04] [Server thread/INFO]: There are 0/30 players online:
[02:02:04] [Server thread/INFO]: 
[02:03:04] [Server thread/INFO]: There are 0/30 players online:
[02:03:04] [Server thread/INFO]: 
[02:03:04] [Server thread/INFO]: com.mojang.authlib.GameProfile@5fb5893f[id=<null>,name=Rileedeadeye,properties={},legacy=false] (/97.84.140.124:49871) lost connection: Disconnected
[02:03:10] [Server thread/INFO]: com.mojang.authlib.GameProfile@7ee58662[id=<null>,name=Rileedeadeye,properties={},legacy=false] (/97.84.140.124:49873) lost connection: Disconnected
[02:04:03] [Server thread/INFO]: There are 0/30 players online:
[02:04:03] [Server thread/INFO]: 
[02:04:20] [User Authenticator #1/INFO]: UUID of player Rileedeadeye is 3fc0051a-11a6-4102-8f0f-c38c16f305c3
[02:04:20] [Server thread/INFO]: Rileedeadeye[/97.84.140.124:49953] logged in with entity id 380 at (-234.374809324321, 66.0, 227.53057490953188)
[02:04:20] [Server thread/INFO]: Rileedeadeye joined the game
[02:04:21] [Server thread/INFO]: [STDOUT]: syncToClient: style = STYLE_FLAT_GRADIENT
[02:05:04] [Server thread/INFO]: There are 1/30 players online:
[02:05:04] [Server thread/INFO]: Rileedeadeye
[02:05:10] [Server thread/INFO]: [Rileedeadeye: Toggled downfall]
[02:05:18] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException: The validated object is null
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_112]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222) ~[minecraft_server.1.11.jar:?]
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203) ~[minecraft_server.1.11.jar:?]
	at net.minecraft.util.NonNullList.add(SourceFile:52) ~[dd.class:?]
	at java.util.AbstractList.add(AbstractList.java:108) ~[?:1.8.0_112]
	at net.minecraft.inventory.Container.func_75138_a(Container.java:59) ~[ack.class:?]
	at net.minecraft.inventory.Container.func_75132_a(Container.java:48) ~[ack.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:100) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2490) ~[aax.class:?]
	at de.ellpeck.actuallyadditions.mod.blocks.BlockFarmer.func_180639_a(BlockFarmer.java:55) ~[BlockFarmer.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:448) ~[lz.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:674) ~[mi.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jm.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jm.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_112]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[02:05:18] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:726) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) ~[lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NullPointerException
	at net.minecraft.item.ItemStack.func_77989_b(ItemStack.java:376) ~[afi.class:?]
	at net.minecraft.inventory.Container.func_75142_b(Container.java:78) ~[ack.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:254) ~[ly.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1987) ~[ajq.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840) ~[lw.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1957) ~[ajq.class:?]
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:650) ~[lw.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1749) ~[ajq.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621) ~[lw.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) ~[MinecraftServer.class:?]
	... 4 more
[02:05:18] [Server thread/ERROR]: This crash report has been saved to: /servers/lgmoddedmc/minecraft/./crash-reports/crash-2016-12-23_02.05.18-server.txt
[02:05:18] [Server thread/INFO]: Stopping server
[02:05:18] [Server thread/INFO]: Saving players
[02:05:18] [Server thread/INFO]: Saving worlds
[02:05:18] [Server thread/INFO]: Saving chunks for level 'Doomcraft'/Overworld
[02:05:18] [Server thread/INFO]: Saving chunks for level 'Doomcraft'/Nether
[02:05:18] [Server thread/INFO]: Saving chunks for level 'Doomcraft'/The End
[02:05:18] [Server thread/INFO]: Saving chunks for level 'Doomcraft'/Cavern
[02:05:18] [Server thread/INFO]: Saving chunks for level 'Doomcraft'/Ruins Cavern
[02:05:18] [Server thread/INFO]: Saving chunks for level 'Doomcraft'/Aqua Cavern
[02:05:18] [Server thread/INFO]: Saving chunks for level 'Doomcraft'/Caveland
[02:05:18] [Server thread/INFO]: Saving chunks for level 'Doomcraft'/Ice Cavern
[02:05:19] [Server Shutdown Thread/INFO]: Stopping server
[02:05:19] [Server Shutdown Thread/INFO]: Saving players

**Comment by canitzp** [comment]
Does this happen with other farmers under the same conditions too?

**Comment by canitzp** [comment]
Which plants are you harvesting?

**Comment by Ellpeck** [comment]
This seems to me like the crop is returning a null itemstack when being harvested or something like that.

**Comment by rileedeadeye** [comment]
Sorry for the delay, holidays and all. So far I have only tested the farmer with wheat. I will however test tonight to see if this happens with other crops.

**Comment by Ellpeck** [comment]
Does this happen with *every* farmer? And it's only the client crashing, correct?
Could you try removing any other mods to see if that fixes it? I never encountered this before I don't think, but I don't have the time to test either.

**Comment by rileedeadeye** [comment]
I will test the issue further tonight once I'm out of work, but it is crashing the server. The client simply gets disconnected from the server.
