### ISSUE TITLE
NullPointerException in server console when using a Ball of Fur

### ISSUE THREAD

**Issue by Ricket** [Ellpeck/ActuallyAdditions#542]
ActuallyAdditions-1.10.2-r90.jar -- in modpack Direwolf20-1.10 version 1.2.1

Using a ball of fur, I get this in the server console:

```
[16:03:16] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
```

There is no stack trace on the cause exception. It might have been hotspot'd. This looks similar to #541 but I saw your fix there was specific to the solidified experience item, so I think this is a different issue. Also similar to 541, it happens on the last ball of fur that I use, if I collect a stack of them.

**Comment by Ellpeck** [comment]
Yea this is like a stupid 1.10 thing that I missed when doing some general changes :v

**Comment by Ellpeck** [comment]
Yea, you can definitely do that.
By the way, I don't know if releasing an update just for these two stack traces would make a whole lot of sense, especially because they don't cause a crash and don't break anything in-game either. :v
