### ISSUE TITLE
AA Guide texture glitch

### ISSUE THREAD

**Issue by g-BonE** [Ellpeck/ActuallyAdditions#601]
There seems to be a bug (missing textures) in the guide right around where it tells You about item laser relays. The book shows black/pink textures and becomes unreadable. Running r98 on 1.10.2. ModPack is based on FTB SkyFactory 3.0.

Screenshot: http://i67.tinypic.com/2hriqnk.png

Relevant log snippet:

`[10:19:59] [Client thread/WARN]: Failed to load texture: actuallyadditions:textures/gui/booklet/page_item_laser_relay_basic.png
java.io.FileNotFoundException: actuallyadditions:textures/gui/booklet/page_item_laser_relay_basic.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68) ~[bww.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[bxi.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:28) ~[bwa.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:67) [bwf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:42) [bwf.class:?]
	at de.ellpeck.actuallyadditions.mod.booklet.page.PagePicture.drawScreenPre(PagePicture.java:38) [PagePicture.class:?]
	at de.ellpeck.actuallyadditions.mod.booklet.gui.GuiPage.drawScreenPre(GuiPage.java:180) [GuiPage.class:?]
	at de.ellpeck.actuallyadditions.mod.booklet.gui.GuiBooklet.func_73863_a(GuiBooklet.java:135) [GuiBooklet.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094) [bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
[10:19:59] [Client thread/WARN]: Failed to load texture: actuallyadditions:textures/gui/booklet/page_item_laser_relay_fail.png
java.io.FileNotFoundException: actuallyadditions:textures/gui/booklet/page_item_laser_relay_fail.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68) ~[bww.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[bxi.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:28) ~[bwa.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:67) [bwf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:42) [bwf.class:?]
	at de.ellpeck.actuallyadditions.mod.booklet.page.PagePicture.drawScreenPre(PagePicture.java:38) [PagePicture.class:?]
	at de.ellpeck.actuallyadditions.mod.booklet.gui.GuiPage.drawScreenPre(GuiPage.java:180) [GuiPage.class:?]
	at de.ellpeck.actuallyadditions.mod.booklet.gui.GuiBooklet.func_73863_a(GuiBooklet.java:135) [GuiBooklet.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094) [bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
[10:20:04] [Client thread/WARN]: Failed to load texture: actuallyadditions:textures/gui/booklet/page_item_laser_relay_transfer.png
java.io.FileNotFoundException: actuallyadditions:textures/gui/booklet/page_item_laser_relay_transfer.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68) ~[bww.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[bxi.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:28) ~[bwa.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:67) [bwf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:42) [bwf.class:?]
	at de.ellpeck.actuallyadditions.mod.booklet.page.PagePicture.drawScreenPre(PagePicture.java:38) [PagePicture.class:?]
	at de.ellpeck.actuallyadditions.mod.booklet.gui.GuiPage.drawScreenPre(GuiPage.java:180) [GuiPage.class:?]
	at de.ellpeck.actuallyadditions.mod.booklet.gui.GuiBooklet.func_73863_a(GuiBooklet.java:135) [GuiBooklet.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094) [bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
[10:20:04] [Client thread/WARN]: Failed to load texture: actuallyadditions:textures/gui/booklet/page_item_laser_relay_whitelist_chest.png
java.io.FileNotFoundException: actuallyadditions:textures/gui/booklet/page_item_laser_relay_whitelist_chest.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68) ~[bww.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[bxi.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:28) ~[bwa.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:67) [bwf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:42) [bwf.class:?]
	at de.ellpeck.actuallyadditions.mod.booklet.page.PagePicture.drawScreenPre(PagePicture.java:38) [PagePicture.class:?]
	at de.ellpeck.actuallyadditions.mod.booklet.gui.GuiPage.drawScreenPre(GuiPage.java:180) [GuiPage.class:?]
	at de.ellpeck.actuallyadditions.mod.booklet.gui.GuiBooklet.func_73863_a(GuiBooklet.java:135) [GuiBooklet.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094) [bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
[10:20:04] [Client thread/WARN]: Failed to load texture: actuallyadditions:textures/gui/booklet/page_item_laser_relay_whitelist_interface.png
java.io.FileNotFoundException: actuallyadditions:textures/gui/booklet/page_item_laser_relay_whitelist_interface.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68) ~[bww.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[bxi.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:28) ~[bwa.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:67) [bwf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:42) [bwf.class:?]
	at de.ellpeck.actuallyadditions.mod.booklet.page.PagePicture.drawScreenPre(PagePicture.java:38) [PagePicture.class:?]
	at de.ellpeck.actuallyadditions.mod.booklet.gui.GuiPage.drawScreenPre(GuiPage.java:180) [GuiPage.class:?]
	at de.ellpeck.actuallyadditions.mod.booklet.gui.GuiBooklet.func_73863_a(GuiBooklet.java:135) [GuiBooklet.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094) [bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
[10:20:04] [Client thread/WARN]: Failed to load texture: actuallyadditions:textures/gui/booklet/page_item_laser_relay_system.png
java.io.FileNotFoundException: actuallyadditions:textures/gui/booklet/page_item_laser_relay_system.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68) ~[bww.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[bxi.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:28) ~[bwa.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:67) [bwf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:42) [bwf.class:?]
	at de.ellpeck.actuallyadditions.mod.booklet.page.PagePicture.drawScreenPre(PagePicture.java:38) [PagePicture.class:?]
	at de.ellpeck.actuallyadditions.mod.booklet.gui.GuiPage.drawScreenPre(GuiPage.java:180) [GuiPage.class:?]
	at de.ellpeck.actuallyadditions.mod.booklet.gui.GuiBooklet.func_73863_a(GuiBooklet.java:135) [GuiBooklet.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094) [bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]`

**Comment by g-BonE** [comment]
Just looked inside the jar file and indeed, the texture files are referenced by a wrong name - for example:

actuallyadditions:textures/gui/booklet/page_item_laser_relay_whitelist_interface.png

in the jar file is named:

actuallyadditions:textures/gui/booklet/pageItemLaserRelayWhitelistInterface.png

**Comment by Ellpeck** [comment]
It's fixed for 1.11 already, but I'll pull this down to 1.10 if I make another update for that.
