### ISSUE TITLE
Forced disconnect when using batteries

### ISSUE THREAD

**Issue by Lost-Ninja** [Ellpeck/ActuallyAdditions#766]
After either making or spawning in (via creative) doing anything with either single or triple batteries forces the client to disconnect with this:
`[18:41:20] [Server thread/INFO]: LostNinja joined the game
[18:41:20] [Server thread/INFO] [Actually Additions]: Sending Player Data to player LostNinja with UUID 3c829db3-6286-457c-b593-9905e8d5a882.
[18:41:20] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:63828
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:406) ~[ly.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:164) ~[mi.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:215) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[er.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [mh.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.IncompatibleClassChangeError: Class romelo333.notenoughwands.Items.MovingWand does not implement the requested interface cofh.api.energy.IEnergyContainerItem
        at romelo333.notenoughwands.varia.ItemCapabilityProvider$1.receiveEnergy(ItemCapabilityProvider.java:37) ~[ItemCapabilityProvider$1.class:?]
        at de.ellpeck.actuallyadditions.mod.items.ItemBattery.func_77663_a(ItemBattery.java:64) ~[ItemBattery.class:?]
        at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:423) ~[afj.class:?]
        at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:347) ~[aax.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:514) ~[aay.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088) ~[sw.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:232) ~[aay.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:329) ~[ly.class:?]
        ... 9 more
[18:41:20] [Server thread/INFO]: LostNinja lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[18:41:20] [Server thread/INFO]: LostNinja left the game
>`
Need to then remove the battery via an NBT editor prior to that client being able to rejoin the world. :(

**Comment by Lost-Ninja** [comment]
Just to add, while I do have both the NotEnoughWands installed (obviously) and have a moving wand in my inventory (I had a different wand the previous time I had this crash) they are set up to use XP as a power source. Should I report this to them instead?

**Comment by Ellpeck** [comment]
Which Minecraft version is this?

**Comment by Lost-Ninja** [comment]
Ah apologies. Minecraft 1.11.2 using as far as I know the latest version of Actual Additions. (ActuallyAdditions-1.11.2-r107.jar)

**Comment by Ellpeck** [comment]
Forwarding this to @McJty as I have no idea why this happens.
