### ISSUE TITLE
keeps crashing

### ISSUE THREAD

**Issue by currimac** [Ellpeck/ActuallyAdditions#79]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 2/29/16 6:36 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: net/minecraftforge/items/wrapper/SidedInvWrapper
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityInventoryBase.<init>(TileEntityInventoryBase.java:43)
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityCoalGenerator.<init>(TileEntityCoalGenerator.java:35)
	at de.ellpeck.actuallyadditions.mod.blocks.BlockCoalGenerator.func_149915_a(BlockCoalGenerator.java:50)
	at net.minecraft.block.Block.createTileEntity(Block.java:1309)
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:830)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:847)
	at net.minecraft.world.World.func_175625_s(World.java:2280)
	at de.ellpeck.actuallyadditions.mod.event.HudEvent.onGameOverlay(HudEvent.java:56)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_35_HudEvent_onGameOverlay_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:851)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:180)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1331)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.items.wrapper.SidedInvWrapper
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityInventoryBase.<init>(TileEntityInventoryBase.java:43)
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityCoalGenerator.<init>(TileEntityCoalGenerator.java:35)
	at de.ellpeck.actuallyadditions.mod.blocks.BlockCoalGenerator.func_149915_a(BlockCoalGenerator.java:50)
	at net.minecraft.block.Block.createTileEntity(Block.java:1309)
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:830)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:847)
	at net.minecraft.world.World.func_175625_s(World.java:2280)
	at de.ellpeck.actuallyadditions.mod.event.HudEvent.onGameOverlay(HudEvent.java:56)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_35_HudEvent_onGameOverlay_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:851)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:180)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['FireFurniture'/153, l='MpServer', x=-341.94, y=71.00, z=438.06]]
	Chunk stats: MultiplayerChunkCache: 10, 10
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 0.00,64.00,256.00 - World: (0,64,256), Chunk: (at 0,4,0 in 0,16; contains blocks 0,0,256 to 15,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 404470 game time, 653704 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 87 total; [EntityPig['Pig'/270, l='MpServer', x=-383.25, y=65.00, z=374.34], EntityCow['Cow'/271, l='MpServer', x=-379.03, y=68.00, z=383.06], EntityBat['Bat'/272, l='MpServer', x=-318.38, y=15.16, z=372.41], EntitySkeleton['Skeleton'/273, l='MpServer', x=-313.50, y=16.00, z=377.50], EntityCreeper['Creeper'/274, l='MpServer', x=-319.50, y=45.00, z=383.50], EntitySheep['Sheep'/275, l='MpServer', x=-316.00, y=65.00, z=377.94], EntityBat['Bat'/276, l='MpServer', x=-285.66, y=26.06, z=405.38], EntityBat['Bat'/277, l='MpServer', x=-281.41, y=26.06, z=401.28], EntityCreeper['Creeper'/278, l='MpServer', x=-280.50, y=16.00, z=466.50], EntityCow['Cow'/279, l='MpServer', x=-392.81, y=63.00, z=508.97], EntityCow['Cow'/280, l='MpServer', x=-389.16, y=63.00, z=509.03], EntitySkeleton['Skeleton'/281, l='MpServer', x=-387.50, y=36.00, z=374.50], EntityPig['Pig'/282, l='MpServer', x=-389.91, y=64.00, z=369.22], EntityZombie['Zombie'/154, l='MpServer', x=-340.47, y=46.00, z=440.22], EntitySkeleton['Skeleton'/155, l='MpServer', x=-348.47, y=60.00, z=447.88], EntityBat['Bat'/284, l='MpServer', x=-337.59, y=24.69, z=362.88], EntityItem['item.item.pickaxeStone'/156, l='MpServer', x=-340.94, y=71.00, z=435.56], EntityPlayerSP['FireFurniture'/153, l='MpServer', x=-341.94, y=71.00, z=438.06], EntityXPOrb['Experience Orb'/158, l='MpServer', x=-348.69, y=53.26, z=428.00], EntityCreeper['Creeper'/159, l='MpServer', x=-347.00, y=58.00, z=459.41], EntityZombie['Zombie'/287, l='MpServer', x=-297.78, y=26.00, z=505.91], EntitySpider['Spider'/160, l='MpServer', x=-352.31, y=60.09, z=451.69], EntityBat['Bat'/289, l='MpServer', x=-288.09, y=18.06, z=506.06], EntityEnderman['Enderman'/163, l='MpServer', x=-327.81, y=50.00, z=463.44], EntityCreeper['Creeper'/165, l='MpServer', x=-306.16, y=36.00, z=436.78], EntityZombie['Zombie'/166, l='MpServer', x=-319.66, y=32.00, z=436.34], EntityZombie['Zombie'/167, l='MpServer', x=-316.50, y=36.00, z=444.50], EntityItem['item.item.rottenFlesh'/168, l='MpServer', x=-342.53, y=47.66, z=476.66], EntitySkeleton['Skeleton'/169, l='MpServer', x=-374.50, y=37.00, z=458.50], EntityZombie['Zombie'/170, l='MpServer', x=-376.50, y=37.00, z=457.50], EntityCow['Cow'/171, l='MpServer', x=-383.25, y=75.00, z=428.19], EntityZombie['Zombie'/299, l='MpServer', x=-366.50, y=51.00, z=361.50], EntityCreeper['Creeper'/180, l='MpServer', x=-328.44, y=17.00, z=408.38], EntityBat['Bat'/181, l='MpServer', x=-317.41, y=38.00, z=420.31], EntityZombie['Zombie'/182, l='MpServer', x=-305.50, y=35.00, z=448.50], EntitySkeleton['Skeleton'/183, l='MpServer', x=-318.75, y=33.00, z=450.13], EntityZombie['Zombie'/184, l='MpServer', x=-324.50, y=47.00, z=477.50], EntityZombie['Zombie'/312, l='MpServer', x=-268.50, y=13.00, z=403.50], EntityEnderman['Enderman'/185, l='MpServer', x=-388.50, y=15.00, z=438.50], EntityCow['Cow'/186, l='MpServer', x=-385.63, y=75.00, z=434.72], EntityBat['Bat'/314, l='MpServer', x=-312.34, y=16.28, z=518.88], EntityCow['Cow'/187, l='MpServer', x=-385.38, y=73.00, z=445.34], EntityCow['Cow'/315, l='MpServer', x=-402.06, y=64.00, z=506.06], EntitySheep['Sheep'/188, l='MpServer', x=-344.00, y=70.00, z=399.94], EntityCreeper['Creeper'/316, l='MpServer', x=-283.50, y=23.00, z=368.50], EntityBat['Bat'/189, l='MpServer', x=-297.75, y=32.10, z=446.75], EntityCow['Cow'/317, l='MpServer', x=-394.91, y=63.00, z=513.06], EntityBat['Bat'/190, l='MpServer', x=-388.28, y=20.31, z=451.47], EntitySkeleton['Skeleton'/191, l='MpServer', x=-389.91, y=11.00, z=416.41], EntityCow['Cow'/319, l='MpServer', x=-421.63, y=64.00, z=483.50], EntityCow['Cow'/192, l='MpServer', x=-390.84, y=74.00, z=427.84], EntitySkeleton['Skeleton'/193, l='MpServer', x=-367.50, y=50.00, z=390.50], EntityZombie['Zombie'/194, l='MpServer', x=-364.88, y=50.00, z=390.59], EntityZombie['Zombie'/195, l='MpServer', x=-366.75, y=50.00, z=389.28], EntitySkeleton['Skeleton'/196, l='MpServer', x=-356.50, y=49.00, z=396.50], EntitySkeleton['Skeleton'/197, l='MpServer', x=-364.50, y=50.00, z=394.50], EntityCreeper['Creeper'/198, l='MpServer', x=-366.50, y=52.00, z=388.50], EntityItem['item.item.arrow'/199, l='MpServer', x=-358.56, y=54.54, z=395.34], EntitySkeleton['Skeleton'/200, l='MpServer', x=-322.31, y=24.00, z=388.28], EntitySheep['Sheep'/201, l='MpServer', x=-324.00, y=67.00, z=386.03], EntitySkeleton['Skeleton'/202, l='MpServer', x=-290.50, y=17.00, z=419.50], EntitySquid['Squid'/204, l='MpServer', x=-289.09, y=58.84, z=454.94], EntityCow['Cow'/206, l='MpServer', x=-380.47, y=68.00, z=388.53], EntityCow['Cow'/207, l='MpServer', x=-380.50, y=68.00, z=387.19], EntityCow['Cow'/208, l='MpServer', x=-378.25, y=69.00, z=392.28], EntitySkeleton['Skeleton'/209, l='MpServer', x=-305.97, y=21.00, z=386.53], EntitySkeleton['Skeleton'/210, l='MpServer', x=-315.50, y=24.00, z=384.50], EntityCreeper['Creeper'/211, l='MpServer', x=-314.50, y=40.00, z=393.50], EntitySkeleton['Skeleton'/212, l='MpServer', x=-318.50, y=33.00, z=389.50], EntityItem['item.item.rottenFlesh'/213, l='MpServer', x=-313.06, y=51.54, z=393.66], EntitySquid['Squid'/214, l='MpServer', x=-302.84, y=51.66, z=470.50], EntitySkeleton['Skeleton'/215, l='MpServer', x=-401.50, y=63.00, z=436.50], EntityBat['Bat'/216, l='MpServer', x=-330.84, y=23.66, z=370.38], EntityCreeper['Creeper'/217, l='MpServer', x=-333.84, y=23.00, z=369.16], EntityBat['Bat'/218, l='MpServer', x=-323.81, y=30.78, z=381.44], EntityZombie['Zombie'/346, l='MpServer', x=-412.50, y=38.00, z=365.50], EntityZombie['Zombie'/219, l='MpServer', x=-323.50, y=40.00, z=377.50], EntityCreeper['Creeper'/347, l='MpServer', x=-411.50, y=38.00, z=363.50], EntityCreeper['Creeper'/220, l='MpServer', x=-325.91, y=45.00, z=371.34], EntityEnderman['Enderman'/221, l='MpServer', x=-281.59, y=17.00, z=424.84], EntityCreeper['Creeper'/222, l='MpServer', x=-285.50, y=14.00, z=462.50], EntitySquid['Squid'/223, l='MpServer', x=-322.75, y=55.25, z=497.25], EntityBat['Bat'/351, l='MpServer', x=-262.25, y=20.09, z=504.25], EntityZombie['Zombie'/224, l='MpServer', x=-398.50, y=55.00, z=386.50], EntityPig['Pig'/225, l='MpServer', x=-389.03, y=67.00, z=390.97], EntitySkeleton['Skeleton'/226, l='MpServer', x=-303.50, y=22.00, z=495.50], EntityZombie['Zombie'/370, l='MpServer', x=-268.50, y=20.00, z=515.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:404)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	CPU: 4x AMD A10-7800 Radeon R7, 12 Compute Cores 4C+8G 
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 325701328 bytes (310 MB) / 942546944 bytes (898 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: Minecraft 1.8.9 MCP 9.19 Powered by Forge 11.15.0.1684 Optifine OptiFine_1.8.9_HD_U_H2 21 mods loaded, 21 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.18} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.0.1684.jar) 
	UCHIJAAAA	Forge{11.15.0.1684} [Minecraft Forge] (forge-1.8.9-11.15.0.1684.jar) 
	UCHIJAAAA	ActuallyAdditions{1.8.9-r26} [Actually Additions] (ActuallyAdditions-1.8.9-r26.jar) 
	UCHIJAAAA	BedrockTools{hotfix1} [BedrockTools] (BedrockTools-1.4.2_hotfix1.jar) 
	UCHIJAAAA	corundum{1.0} [Corundum Ore Mod] (Curundum-1.1(1.8.9).jar) 
	UCHIJAAAA	Extra_Diamonds_Mod{5.2.0} [extra_diamonds_mod] (EDM-5.2.0.jar) 
	UCHIJAAAA	furnus{1.7} [Furnus] (Furnus-1.8.9-1.7.jar) 
	UCHIJAAAA	ironbackpacks{1.8.9-2.0.2} [Iron Backpacks] (IronBackpacks-1.8.9-2.0.2.jar) 
	UCHIJAAAA	morearmor{1.8.9-1.2.0} [More Armor] (morearmor-1.8.9-1.2.0.jar) 
	UCHIJAAAA	notenoughwands{1.2.8} [Not Enough Wands] (notenoughwands-1.8.9-1.2.8.jar) 
	UCHIJAAAA	practicalities{2.0.0-b6} [Practicalities] (Practicalities-Mod-1.8.9 (5).jar) 
	UCHIJAAAA	Roguelike{1.4.5} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.4.5.jar) 
	UCHIJAAAA	SilentGems{1.3.9b} [Silent's Gems] (SilentsGems-1.8.9-1.3.9b-102.jar) 
	UCHIJAAAA	Talismans 2{2.2.0} [Talismans 2] (Talismans2-1.8.9-2.2.0.jar) 
	UCHIJAAAA	guru{1.0} [The Basic Elements] (The Basic Elementsv2-1.2.1-1.8.9.jar) 
	UCHIJAAAA	ToolsOnTheGo{1.8.9} [Tools on the Go] (ToolsOnTheGo-1.8.9.1.2.1.jar) 
	UCHIJAAAA	ultimate_unicorn_mod{1.4.1} [Wings, Horns, and Hooves, the Ultimate Unicorn Mod!] (ultimate_unicorn_mod-1.8.9-1.4.1.jar) 
	UCHIJAAAA	usefulrecipes{1.1} [UsefulRecipes] (UsefulRecipes-1.1.0(1.8.9).jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13397 Compatibility Profile Context 15.200.1055.0' Renderer: 'AMD Radeon(TM) R7 Graphics'
	Launched Version: 1.8.9-forge1.8.9-11.15.0.1684
	XRay Version: 4.5
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) R7 Graphics GL version 4.5.13397 Compatibility Profile Context 15.200.1055.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A10-7800 Radeon R7, 12 Compute Cores 4C+8G

**Comment by Ellpeck** [comment]
Your Forge version is outdated.
