### ISSUE TITLE
Ticking Player crash when entering world

### ISSUE THREAD

**Issue by LukaPix** [Ellpeck/ActuallyAdditions#808]
Happens when trying to enter a World (already created ones and new ones)
I have Optifine installed so i tried without it but it didnt make a difference.

Minecraft: 1.11.2
Forge: 13.20.0.2315
Actually Additions: r106

```
java.lang.NullPointerException: Ticking player
	at de.ellpeck.actuallyadditions.mod.data.PlayerData.getDataFromPlayer(PlayerData.java:32)
	at de.ellpeck.actuallyadditions.mod.items.ItemWingsOfTheBats.livingUpdateEvent(ItemWingsOfTheBats.java:124)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_67_ItemWingsOfTheBats_livingUpdateEvent_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:531)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2005)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:232)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:329)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:164)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:215)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)
```

Full log : [https://1drv.ms/t/s!An8Z2izmI8NLgpJWyiSBqJppY3rP7A](https://1drv.ms/t/s!An8Z2izmI8NLgpJWyiSBqJppY3rP7A)

**Comment by LukaPix** [comment]
If it helps, i figured out it only happens if dynamic surroundings is installed, if i remove it everythings works fine.
