### ISSUE TITLE
[1.12 - r115] Game randomly crashes on load... rare... like 1 in 20.

### ISSUE THREAD

**Issue by faceofcat** [Ellpeck/ActuallyAdditions#849]
and yeah... this happens when ran from IntelliJ while developing my mod... maybe related... :S

**error:**
```
Caused by: java.lang.NullPointerException
--
  | at de.ellpeck.actuallyadditions.mod.misc.apiimpl.LaserRelayConnectionHandler.getNetworkFor(LaserRelayConnectionHandler.java:110) ~[LaserRelayConnectionHandler.class:?]
  | at de.ellpeck.actuallyadditions.mod.tile.TileEntityLaserRelay.getNetwork(TileEntityLaserRelay.java:139) ~[TileEntityLaserRelay.class:?]
  | at de.ellpeck.actuallyadditions.mod.tile.TileEntityLaserRelayItem.saveDataOnChangeOrWorldStart(TileEntityLaserRelayItem.java:102) ~[TileEntityLaserRelayItem.class:?]
  | at de.ellpeck.actuallyadditions.mod.blocks.base.BlockContainerBase.neighborsChangedCustom(BlockContainerBase.java:151) ~[BlockContainerBase.class:?]
  | at de.ellpeck.actuallyadditions.mod.blocks.base.BlockContainerBase.onNeighborChange(BlockContainerBase.java:166) ~[BlockContainerBase.class:?]
  | at net.minecraft.world.World.updateComparatorOutputLevel(World.java:4132) ~[World.class:?]
  | at net.minecraft.tileentity.TileEntity.markDirty(TileEntity.java:178) ~[TileEntity.class:?]
  | at net.ndrei.teslacorelib.tileentities.ElectricTileEntity$initializeInventories$1.onChanged(ElectricTileEntity.kt:32) ~[ElectricTileEntity$initializeInventories$1.class:?]
  | at net.ndrei.teslacorelib.inventory.EnergyStorage.takePower(EnergyStorage.kt:171) ~[EnergyStorage.class:?]
  | at net.ndrei.teslacorelib.inventory.EnergyStorage.takePower(EnergyStorage.kt:70) ~[EnergyStorage.class:?]
  | at net.ndrei.teslacorelib.tileentities.ElectricMachine.protectedUpdate(ElectricMachine.kt:229) ~[ElectricMachine.class:?]
  | at net.ndrei.teslacorelib.tileentities.ElectricTileEntity.innerUpdate(ElectricTileEntity.kt:162) ~[ElectricTileEntity.class:?]
  | at net.ndrei.teslacorelib.tileentities.SidedTileEntity.update(SidedTileEntity.kt:777) ~[SidedTileEntity.class:?]
  | at net.minecraft.world.World.updateEntities(World.java:1966) ~[World.class:?]
  | at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:644) ~[WorldServer.class:?]
  | at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:836) ~[MinecraftServer.class:?]
```

**full log:**
https://gist.github.com/faceofcat/18ce9690014461405fa06dc9ae902310

**Comment by Shadows-of-Fire** [comment]
Face, i'll go add the nullcheck, but something tells me you shouldn't be having null tile entities in the first place, like the last issue.

**Comment by faceofcat** [comment]
I'm pretty sure I don't have null tile entities... :S... not on purpose anyway... are you sure that was the cause of both these issues?

**Comment by Shadows-of-Fire** [comment]
The first issue was due to a null tile on your end.  This one just makes no damn sense.

**Comment by Ellpeck** [comment]
rip

**Comment by faceofcat** [comment]
null tile like in a null tile entity?... :S... how the hell would that even be possible?... I'm not doing anything weird with tile entities...

hmm... maybe... an event gets out wrongfully during world load and stuff tries to update while a neighbor entity hasn't been loaded yet?... :S... I'll try to see if I can figure that out...

thanks guys!
